merely-useful/merely-useful.github.io

- .travis.yml
- Makefile
1.  Use `wildcard` in `Makefile` to pick up all dependencies - will add image dependencies later.
2.  Modify `.travis.yml` to run `make`.
I don't know how to test this locally...
> Switching to Makefile for Travis

- meetings/2019-05-09.md
The final consensus was to choose one IDE to focus on, and that that IDE will be Spyder.
> Notes from Python tool choice meeting

- index.Rmd
> Reformatting authors.

- meetings/2019-05-13.md
-   Closes #53 (pass)
-   Closes #33 (work in forks)
-   Closes #50 (pass)
-   Closes #59 (pass)
-   Closes #56 (pass)
> Meeting minutes 2019-05-13

- README.md
Related to #65 (only for R packages)
> Explanation to README about using R packages in book

- README.md
- intermediate-goals.Rmd
- meetings/2019-05-13.md
Here's a first go at an outline for the intermediate course. Would love to hear people's comments before merging.
> Intermediate outline

- Makefile
- README.md
- bin/chunks.py
- bin/gloss.py
- bin/links.py
- bin/test_chunks.py
- bin/util.py
- etc/links.md
- novice-goals.Rmd
-   Fixed missing/unused links uncovered by checking.
-   Modified utilities to prevent spurious reports because of `[...][...]` in code fragments.
Still get warnings because of badly-formatted code block headers in legacy files, but they're all for real - I think this is ready to merge.
> Building checking utilities.

- README.md
> Add to README about inserting suggestions when reviewing PRs

- _bookdown.yml
More for visually separating the included Rmd files for the bookdown.yml file.
> Simple visual separation of Rmd files in _bookdown.yml file

- novice-goals.Rmd
- objectives/reproducibility.md
- py-reproducibility.Rmd
@gvwilson good enough for now?
> moving path and data material

- r-data-manipulation.Rmd
Minor fix to clean up some files after "saving data" section in r-data-manipulation...must be a [tidy kiwi](beatidykiwi.nz).
> Avoid creating shrapnel in r-data-manipulation

- rse-bash.Rmd
@gvwilson asked me to go through a few files and help with some editing. Here are a a few suggestions for the shell material. I hope there is not too much overlap with what you're doing @gvwilson, sorry I thought you were not starting the edits quite yet.
Note, still draft status because I am going through the second part of the file right now.
> Rse bash suggestions

- r-publishing.Rmd
@cwickham I adapted your material to the respective Python chapter and wanted to suggest some of the changes "upstream". Let me know which you want to incorporate and which to revert.
> Review r-pub after making py-pub

- gloss.md
- links.md
- style.Rmd
@gvwilson Since there are a few bigger changes I felt more comfortable with a PR rather than directly merging.
> Style suggestions

- rse-bash.Rmd
@gwilson Aside from my suggested changes in the PR, see issue #220.
> Rse bash review

- _bookdown.yml
- keypoints/r-getting-started.md
- objectives/r-getting-started.md
- questions/r-getting-started.md
- r-getting-started.Rmd
resolves #95 
I've used the Python Getting Started files as a template and have started to adapt the material for R and RStudio. A few notes are included in the .Rmd to also accommodate #111 and #183 
I'm open to suggestions for whether the instructions should reference saving generic scripts (.R) or .Rmd files (or R notebooks). I'm leaving generic for now.
> Novice R: Getting started

- py-jupyter.md
This is introducing jupyterlab and jupytext. I haven't added exercises yet, but I won't have time to do that for a while so I think the rest of the material could benefit from a review in the meanwhile. Maybe @mbonsma or @dhavide since you both have experience with jupytext.
I am open to dicuss other source formats instead of .Rmd also, in case you have another preference.
> Jupyerlab and jupytext

- rse-ci.Rmd
- rse-git-advanced.Rmd
> Adding missing captions

- rse-project.Rmd
This is slightly hurried formatting and will need editing for content, style, and formatting..
> adding draft of the project documentation

- rse-teams.Rmd
Love a lot of the new work in this chapter!
I've made some corrections and suggestions for things about teams. I have some larger level comments that I'll file an issue for once this is settled.
> proposing some corrections and suggestions

- _py-rse.yml
- links.md
- py-rse-index.Rmd
This PR introduces the data analysis task that we'll be tackling (verification of Zipf's law in a bunch of classic English novels) as per #240.
> Introducing Zipf's law

- zipfs-law/bin/collate.py
- zipfs-law/bin/countwords.py
- zipfs-law/bin/plotcounts.py
Some suggestions that popped up when I was working with the scripts. Sorry that I didn't find time to review more thoroughly in your previous PR @DamienIrving. None of these suggestions changes the behavior or usage of the scripts.
@elliewix could you confirm whether it is correct that raw strings are to be used with regex to prevent unexpected Python string processing before the string reaches the regex engine?
> Zipf scripts suggestions

- zipfs-law/bin/plotcounts_config.py
We should update this file also, right @DamienIrving ? As in #333
> Avoid log of 0 when beta is 1 for plotconfig file

- links.md
- py-rse/publish.Rmd
This one is ready to review. 
@k8hertweck - It has a little bit of overlap with the project structure and teams chapters, so maybe you'd be a good reviewer?
> Zipf's updates to publishing chapter

- .gitignore
- Makefile
- _output.yml
- _py-rse.yml
- preamble.tex
- py-rse-index.Rmd
- py-rse/bash-basics.Rmd
- py-rse/ci.Rmd
- py-rse/configuration.Rmd
- py-rse/correct.Rmd
- py-rse/errors.Rmd
- py-rse/install.Rmd
- py-rse/project.Rmd
- py-rse/style.Rmd
- py-rse/teams.Rmd
1.  Use 'book' as documentclass instead of 'Nemilov' to circumvent problems with Unicode.
2.  Add a bunch of shrapnel to `.gitignore`.
> Getting a clean build:

- py-rse/package-py.Rmd
- py-rse/py-scripting.Rmd
- py/development.Rmd
Reverts merely-useful/merely-useful.github.io#341
I have more changes locally that are rebased on book, so I am reverting this PR and opening a new one.
> Revert "Package section zipf updates"

- py-rse/bash-basics.Rmd
- correcting typo
- resolving FIXME about Linux `ls -F`
- note about Amira as main character
> Quick fixes to p-rse/bash-basics.Rmd

- py-rse/configuration.Rmd
- py-rse/git-advanced.Rmd
- py-rse/git-cmdline.Rmd
- py-rse/py-scripting.Rmd
- zipfs-law/bin/plotcounts.py
Turns out the code was fine...just some re-wording to clarify the constant of proportionality.
> Clarify the constant of proportionality, closes #367

- py-rse/bash-advanced.Rmd
- py-rse/bash-basics.Rmd
Updating exercises for both bash chapters so they don't require additional data
> Bash exercises for RSE book

- book.bib
Refer to Tierny & Ram somewhere in the book.
> Adding Tierny reference

- py-rse/git-advanced.Rmd
- py-rse/packaging.Rmd
- py-rse/scripting.Rmd
- zipf/bin/utilities.py
- zipf/requirements.txt
After #402 was merged I realised there was a few more updates I should have made.
We still need to resolve #410, but for now this PR just needs to be merged before @gvwilson does the editing pass on `packaging.md`.
> More updates to packaging chapter

- _py-rse.yml
- py-rse/automate.Rmd
- py-rse/bash-advanced.Rmd
- py-rse/bash-basics.Rmd
- py-rse/config.Rmd
- py-rse/errors.Rmd
- py-rse/finale.Rmd
- py-rse/git-advanced.Rmd
- py-rse/git-cmdline.Rmd
- py-rse/keypoints.Rmd
- py-rse/objectives.Rmd
- py-rse/packaging.Rmd
- py-rse/project.Rmd
- py-rse/solutions.Rmd
- py-rse/ssh.Rmd
- py-rse/style.Rmd
- py-rse/teams.Rmd
- py-rse/testing.Rmd
Related to #421, but does not resolve it.
I included `style.Rmd` right after `scripting.Rmd`. I've done a quick scan over linkage between the new arrangement.
I've kept the `publishing.Rmd` in the outline for now, so that #422 can be finished and merged.
@DamienIrving do you want to have a quick look over this then I will merge and @cwickham can start her review from the main branch.
> Re arranging content

- py-rse-index.Rmd
- py-rse/bash-advanced.Rmd
- py-rse/style.Rmd
Using this PR for any changes I can make directly, otherwise I'm opening issues.
> Review of reordering 

- _bookdown.yml
- questions/r-joins.md
- r-joins.Rmd
A place to hold existing material for joins. See #186
> Novice R: Joins

- py-join.Rmd
This is as far as I got on the join material before we decided to move it to a different section (#197).
> Draft python join material

- novice-goals.Rmd
Missing Data section: A few learning objectives, lecture notes and exercises added
> Add missing values materials, first

- py-rse-index.Rmd
- py-rse/packaging.Rmd
- py-rse/provenance.Rmd
Addresses https://github.com/merely-useful/merely-useful.github.io/pull/431#issuecomment-663716241
> Working the old project content into provenance chapter

- py-rse/automate.Rmd
- py-rse/bash-advanced.Rmd
- py-rse/config.Rmd
- py-rse/errors.Rmd
- py-rse/git-advanced.Rmd
- py-rse/git-cmdline.Rmd
- py-rse/packaging.Rmd
- py-rse/provenance.Rmd
- py-rse/scripting.Rmd
- py-rse/solutions.Rmd
- py-rse/teams.Rmd
- py-rse/testing.Rmd
- py-rse/tree.Rmd
- zipf/bin/script_template.py
I found more minor inconsistencies in the handling of the file tree through the book.
> Small fixes to ensure narrative/tree consistency
